## problem statement :
build a Machine learning model to accurately predict whether or not the patients in the datasets have diabets or not.

## Import necessary libraries

In [5]:
import pandas as pd
import keras
import warnings
warnings.filterwarnings("ignore")
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from keras.layers import Dense,Dropout
from keras.models import Sequential
from keras.models import load_model

## import data

In [8]:
diabetics_data=pd.read_csv("diabetes.csv")
diabetics_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

## Data understanding

In [9]:
diabetics_data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
diabetics_data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [11]:
diabetics_data.shape

(768, 9)

## Data preprocessing

In [13]:
x=diabetics_data.drop("Outcome",axis=1)
y=diabetics_data["Outcome"]

In [14]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [15]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

## Model building

In [21]:
model=Sequential()
model.add(Dense(units=13,input_dim=8,kernel_initializer="uniform",activation="relu"))
model.add(Dense(units=8,kernel_initializer="uniform",activation="relu"))
model.add(Dense(units=1,kernel_initializer="uniform",activation="sigmoid"))
#model.summary()

In [23]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [27]:
 x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.20,random_state=123,shuffle=True,stratify=y)

In [28]:
x_test.shape,y_test.shape

((154, 8), (154,))

In [29]:
x_train.shape,y_train.shape

((614, 8), (614,))

### Alert:- Here's where you need to apply standardization fit_transform,transform

In [32]:
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

## MODEL TRAINING || MODEL TESTING || MODEL EVALUATION

In [34]:
model.fit(  x=x_train,
    y=y_train,
    batch_size=16,
    epochs=50,validation_split=0.2)

Epoch 1/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - accuracy: 0.6395 - loss: 0.6909 - val_accuracy: 0.6992 - val_loss: 0.6852
Epoch 2/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6395 - loss: 0.6804 - val_accuracy: 0.6992 - val_loss: 0.6585
Epoch 3/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6395 - loss: 0.6504 - val_accuracy: 0.6992 - val_loss: 0.5973
Epoch 4/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6395 - loss: 0.6029 - val_accuracy: 0.6992 - val_loss: 0.5247
Epoch 5/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6477 - loss: 0.5613 - val_accuracy: 0.7236 - val_loss: 0.4865
Epoch 6/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7373 - loss: 0.5416 - val_accuracy: 0.7967 - val_loss: 0.4669
Epoch 7/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7617 - loss: 0.5307 - val_accuracy: 0.7967 - val_loss: 0.4550
Epoch 8/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7658 - loss: 0.5201 - val_accuracy: 0.7967 - val_loss: 0.4495
Epoch 9/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7678 - loss: 0.5119 - val_accuracy: 0.7886 - val_loss: 0.4436
Epoch 10/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.5043 - val_accuracy: 0.7967 - val_loss: 0.4401
Epoch 11/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.4972 - val_accuracy: 0.7886 - val_loss: 0.4370
Epoch 12/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7739 - loss: 0.4917 - val_accuracy: 0.7886 - val_loss: 0.4357
Epoch 13/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7739 - loss: 0.4881 - val_accuracy: 0.7967 - val_loss: 0.4307
Epoch 14/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7678 - loss: 0.4839 - val_accuracy: 0.7805 - val_loss: 0.4331
Epoch 15/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7699 - loss: 0.4801 - val_accuracy: 0.7805 - val_loss: 0.4290
Epoch 16/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7637 - loss: 0.4790 - val_accuracy: 0.7805 - val_loss: 0.4275
Epoch 17/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7719 - loss: 0.4759 - val_accuracy: 0.7724 - val_loss: 0.4307
Epoch 18/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7658 - loss: 0.4738 - val_accuracy: 0.7805 - val_loss: 0.4285
Epoch 19/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7658 - loss: 0.4722 - val_accuracy: 0.7805 - val_loss: 0.4283
Epoch 20/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7699 - loss: 0.4709 - val_accuracy: 0.7724 - val_loss: 0.4319
Epoch 21/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7617 - loss: 0.4697 - val_accuracy: 0.7724 - val_loss: 0.4290
Epoch 22/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7617 - loss: 0.4681 - val_accuracy: 0.7724 - val_loss: 0.4290
Epoch 23/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7678 - loss: 0.4672 - val_accuracy: 0.7642 - val_loss: 0.4311
Epoch 24/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7699 - loss: 0.4663 - val_accuracy: 0.7642 - val_loss: 0.4333
Epoch 25/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7760 - loss: 0.4662 - val_accuracy: 0.7642 - val_loss: 0.4332
Epoch 26/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7739 - loss: 0.4642 - val_accuracy: 0.7642 - val_loss: 0.4340
Epoch 27/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7699 - loss: 0.4640 - val_accuracy: 0.7642 - val_loss: 0.4331
Epoch 28/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7699 - loss: 0.4636 - val_accuracy: 0.7642 - val_loss: 0.4339
Epoch 29/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7719 - loss: 0.4624 - val_accuracy: 0.7642 - val_loss: 0.4342
Epoch 30/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7719 - loss: 0.4624 - val_accuracy: 0.7642 - val_loss: 0.4325
Epoch 31/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7739 - loss: 0.4617 - val_accuracy: 0.7805 - val_loss: 0.4329
Epoch 32/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7719 - loss: 0.4614 - val_accuracy: 0.7724 - val_loss: 0.4337
Epoch 33/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7780 - loss: 0.4601 - val_accuracy: 0.7642 - val_loss: 0.4350
Epoch 34/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7739 - loss: 0.4605 - val_accuracy: 0.7805 - val_loss: 0.4320
Epoch 35/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7780 - loss: 0.4597 - val_accuracy: 0.7642 - val_loss: 0.4358
Epoch 36/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7800 - loss: 0.4590 - val_accuracy: 0.7805 - val_loss: 0.4339
Epoch 37/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7719 - loss: 0.4591 - val_accuracy: 0.7805 - val_loss: 0.4337
Epoch 38/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7821 - loss: 0.4578 - val_accuracy: 0.7642 - val_loss: 0.4364
Epoch 39/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7800 - loss: 0.4577 - val_accuracy: 0.7886 - val_loss: 0.4360
Epoch 40/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7800 - loss: 0.4569 - val_accuracy: 0.7724 - val_loss: 0.4359
Epoch 41/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7780 - loss: 0.4570 - val_accuracy: 0.7642 - val_loss: 0.4376
Epoch 42/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7841 - loss: 0.4566 - val_accuracy: 0.7724 - val_loss: 0.4384
Epoch 43/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7800 - loss: 0.4561 - val_accuracy: 0.7805 - val_loss: 0.4369
Epoch 44/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7780 - loss: 0.4556 - val_accuracy: 0.7805 - val_loss: 0.4391
Epoch 45/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7780 - loss: 0.4553 - val_accuracy: 0.7805 - val_loss: 0.4381
Epoch 46/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7780 - loss: 0.4557 - val_accuracy: 0.7724 - val_loss: 0.4427
Epoch 47/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7821 - loss: 0.4548 - val_accuracy: 0.7886 - val_loss: 0.4406
Epoch 48/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7800 - loss: 0.4550 - val_accuracy: 0.7886 - val_loss: 0.4395
Epoch 49/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7800 - loss: 0.4546 - val_accuracy: 0.7886 - val_loss: 0.4424
Epoch 50/50
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7800 - loss: 0.4532 - val_accuracy: 0.7886 - val_loss: 0.4425

## Model prediction

In [41]:
y_pred=model.predict(x_test)
y_pred=(y_pred>0.60).astype(int)
y_pred

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

array([[0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0]])

In [39]:
model.save("diabetics_data.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

### Bonus :- here you can check other metric,for structured data

In [43]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.92      0.84       100
           1       0.77      0.50      0.61        54

    accuracy                           0.77       154
   macro avg       0.77      0.71      0.72       154
weighted avg       0.77      0.77      0.76       154

[[92  8]
 [27 27]]

## New input prediction

## Write down the prediction you did while training

In [44]:
from keras.models import load_model
intelligence_data=load_model("diabetics_data.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [45]:
new_data=np.array([[6,148,72,35,0,33.6,0.627,50]])
new_data=scalar.transform(new_data)
prob=intelligence_data.predict(new_data)
print("probability",prob)
final_class=(prob>0.5).astype(int)
print("final_class",final_class[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step
probability [[0.6351205]]
final_class 1

# THE END!